create table usuarios (
id INT AUTO_INCREMENT NOT NULL,
Nombre VARCHAR(25) NOT NULL, 
Apellido VARCHAR(25) NOT NULL, 
Cedula INT(8) PRIMARY KEY, 
Fecha DATE NOT NULL, 
Genero VARCHAR(10), 
Email VARCHAR(40), 
Clave VARCHAR(40)
) ENGINE=InnoDB;